version: '3'

services:
  llm_inference:
    image: ghcr.io/huggingface/text-generation-inference:1.3
    ports:
      - "8080:80"
    volumes:
      - ./hf_models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--model-id", "mlabonne/NeuralMarcoro14-7B",
              "--revision", "0632ea9f247528ddb7e0f3251f6a16353eca7dd3",
              "--sharded", "false",
              "--max-concurrent-requests", "1",
              "--max-best-of", "16",
              "--max-input-length", "24576",
              "--max-batch-prefill-tokens", "32768",
              "--max-total-tokens", "32768"]