version: '3'

services:
  llm_inference:
    image: ghcr.io/huggingface/text-generation-inference:1.3
    ports:
      - "8080:80"
    volumes:
      - ./hf_models:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ["--model-id", "CultriX/MistralTrix-v1"]